const PHOTO_COUNT=17;
const photos=Array.from({length:PHOTO_COUNT},(_,i)=>({id:i+1,url:"https://picsum.photos/seed/memory-photo-"+(i+1)+"/700/700"}));
const $=id=>document.getElementById(id); const screens=["setup","lobby","join","game","end"];
let role="",peer=null,hostConn=null,roomId="",me=null,hostState=null;
function show(id){screens.forEach(s=>$(s).classList.toggle("hidden",s!==id))}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}
function setHint(id,msg){const el=$(id);if(el)el.textContent=msg}
function peerErrorMessage(e){const m={"peer-unavailable":"La partie n’est plus accessible. Demandez à l’organisateur de recréer une partie.","network":"Connexion au serveur impossible. Vérifiez votre connexion Internet.","server-error":"Le serveur de connexion ne répond pas. Réessayez dans quelques secondes.","socket-error":"La connexion réseau a échoué. Réessayez.","browser-incompatible":"Ce navigateur ne prend pas correctement en charge la connexion nécessaire au jeu.","ssl-unavailable":"La connexion sécurisée n’a pas pu être établie.","unavailable-id":"Cette salle existe déjà. Créez une nouvelle partie."};return m[e?.type]||("Erreur de connexion ("+(e?.type||"inconnue")+"). Réessayez.")}
function makePeer(id){if(typeof Peer!=="function")throw new Error("peerjs_missing");return new Peer(id||undefined,{host:"0.peerjs.com",port:443,path:"/",secure:true,debug:1,config:{iceServers:[{urls:"stun:stun.l.google.com:19302"}]}})}
function pairCount(n){return n+7}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function makeDeck(n){const chosen=photos.slice(0,pairCount(n));return shuffled([...chosen,...chosen].map((p,i)=>({uid:i,pair:p.id,img:p.url,matched:false})))}
function cleanName(v){return (v||"Joueur").trim().replace(/[^\p{L}\p{N} _-]/gu,"").slice(0,18)||"Joueur"}
function randomId(){return "mem-"+Math.random().toString(36).slice(2,10)}
function roomLink(id){return location.origin+location.pathname+"?room="+encodeURIComponent(id)}
function currentPlayer(){return hostState&&hostState.players.find(p=>p.id===hostState.turn)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderLobby(){ $("roomCode").textContent=roomId; $("shareUrl").value=roomLink(roomId); $("playerList").innerHTML=hostState.players.map(p=>'<span class="player-chip">'+escapeHtml(p.name)+(p.id===me.id?" (vous)":"")+"</span>").join(""); const enough=hostState.players.length>=2; $("startBtn").disabled=!enough; $("lobbyHint").textContent=enough?hostState.players.length+" joueurs prêts. Vous pouvez lancer la partie.":"En attente des joueurs… ("+hostState.players.length+"/"+hostState.maxPlayers+")"}
function renderScores(){ $("scores").innerHTML=hostState.players.map(p=>'<div class="score '+(p.id===hostState.turn?"active":"")+'">'+escapeHtml(p.name)+" <strong>"+p.score+" paire"+(p.score>1?"s":"")+"</strong></div>").join(""); const cp=currentPlayer(); $("turnText").textContent=cp?(cp.id===me.id?"C'est à vous de jouer !":"C'est au tour de "+cp.name):""; $("gameInfo").textContent=hostState.foundPairs+"/"+hostState.totalPairs+" paires trouvées • les cartes se cachent après 3 secondes"}
function renderBoard(){const canPlay=hostState.phase==="playing"&&hostState.turn===me.id&&hostState.openIds.length===0; $("board").innerHTML=hostState.deck.map(c=>{const open=c.matched||hostState.openIds.includes(c.uid); return '<button class="tile '+(open?"flipped ":"")+(c.matched?"matched":"")+'" data-id="'+c.uid+'" '+((!canPlay||open)?"disabled":"")+'><span class="tile-inner"><span class="face back"></span><span class="face front"><img src="'+c.img+'" alt="Photo"></span></span></button>'}).join(""); $("board").querySelectorAll(".tile").forEach(b=>b.addEventListener("click",()=>move(Number(b.dataset.id))))}
function renderGame(){renderScores();renderBoard()}
function renderEnd(){ $("finalScores").innerHTML=hostState.players.map(p=>'<div class="final-row"><span>'+escapeHtml(p.name)+'</span><strong>'+p.score+" paire"+(p.score>1?"s":"")+"</strong></div>").join(""); show("end")}
function broadcast(msg){(hostState.connections||[]).forEach(c=>{if(c.open)c.send(msg)})}
function sendState(target){const safe={phase:hostState.phase,maxPlayers:hostState.maxPlayers,totalPairs:hostState.totalPairs,foundPairs:hostState.foundPairs,deck:hostState.deck,openIds:hostState.openIds,turn:hostState.turn,players:hostState.players}; const msg={type:"state",state:safe}; if(target){if(target.open)target.send(msg)}else broadcast(msg)}
function addPlayer(conn,name){if(hostState.phase!=="lobby"||hostState.players.length>=hostState.maxPlayers){conn.send({type:"error",message:"Cette partie est complète ou déjà commencée."});return} const p={id:conn.peer,name:cleanName(name),score:0}; conn.playerId=p.id; hostState.players.push(p); hostState.connections.push(conn); conn.on("close",()=>{hostState.connections=hostState.connections.filter(c=>c!==conn); broadcast({type:"notice",message:p.name+" a quitté la partie."});}); conn.on("data",data=>handleHostMessage(conn,data)); conn.send({type:"welcome",player:p}); sendState(); renderLobby()}
function handleHostMessage(conn,data){if(!data||typeof data!=="object")return; if(data.type==="move"&&hostState.phase==="playing"&&conn.playerId===hostState.turn)hostMove(data.id,conn); if(data.type==="rematch"&&hostState.phase==="finished"){resetGame();sendState();renderGame();show("game")}}
function startGame(){if(hostState.players.length<2)return; hostState.phase="playing";hostState.deck=makeDeck(hostState.players.length);hostState.totalPairs=pairCount(hostState.players.length);hostState.foundPairs=0;hostState.openIds=[];hostState.turn=hostState.players[0].id;hostState.players.forEach(p=>p.score=0);sendState();renderGame();show("game")}
function hostMove(id,conn){if(hostState.openIds.length>=2)return; const card=hostState.deck.find(c=>c.uid===id); if(!card||card.matched||hostState.openIds.includes(id))return; hostState.openIds.push(id);sendState();renderGame(); if(hostState.openIds.length===2){const a=hostState.deck.find(c=>c.uid===hostState.openIds[0]),b=hostState.deck.find(c=>c.uid===hostState.openIds[1]); if(a.pair===b.pair){setTimeout(()=>{a.matched=b.matched=true;hostState.foundPairs++;const p=hostState.players.find(x=>x.id===hostState.turn);if(p)p.score++;hostState.openIds=[];if(hostState.foundPairs>=hostState.totalPairs){hostState.phase="finished";sendState();renderEnd()}else{sendState();renderGame()}},3000)}else{setTimeout(()=>{hostState.openIds=[];const i=hostState.players.findIndex(p=>p.id===hostState.turn);hostState.turn=hostState.players[(i+1)%hostState.players.length].id;sendState();renderGame()},3000)}}}
function move(id){if(role==="host"){if(hostState.turn===me.id)hostMove(id,null)}else if(hostConn&&hostConn.open)hostConn.send({type:"move",id})}
function resetGame(){hostState.phase="playing";hostState.deck=makeDeck(hostState.players.length);hostState.totalPairs=pairCount(hostState.players.length);hostState.foundPairs=0;hostState.openIds=[];hostState.players.forEach(p=>p.score=0);hostState.turn=hostState.players[0].id}
function handleGuestData(data){if(data.type==="welcome"){me=data.player;show("game")} if(data.type==="state"){hostState=data.state;if(hostState.phase==="finished")renderEnd();else if(hostState.phase==="lobby"){renderLobby();show("lobby")}else{renderGame();show("game")}} if(data.type==="notice")toast(data.message); if(data.type==="error"){$("joinHint").textContent=data.message;show("join")}}
function createHost(){if(typeof Peer!=="function"){toast("Le module de connexion ne s’est pas chargé. Actualisez la page.");return}role="host";me={id:randomId(),name:cleanName($("hostName").value)};const max=Number($("playerCount").value);$("createBtn").disabled=true;toast("Création de la salle…");try{peer=makePeer(randomId());peer.on("open",id=>{roomId=id;hostState={phase:"lobby",maxPlayers:max,totalPairs:pairCount(max),foundPairs:0,deck:[],openIds:[],turn:me.id,players:[{id:me.id,name:me.name,score:0}],connections:[]};show("lobby");renderLobby();toast("Salle créée !")});peer.on("connection",conn=>{conn.on("data",data=>{if(data&&data.type==="join")addPlayer(conn,data.name)});conn.on("error",e=>toast(peerErrorMessage(e)))});peer.on("error",e=>{toast(peerErrorMessage(e));$("createBtn").disabled=false})}catch(e){toast("Impossible de créer la partie. Actualisez la page.");$("createBtn").disabled=false}}
function joinRoom(){if(typeof Peer!=="function"){setHint("joinHint","Le module de connexion ne s’est pas chargé. Actualisez la page.");return}role="guest";me={id:randomId(),name:cleanName($("joinName").value)};roomId=new URLSearchParams(location.search).get("room");if(!roomId){setHint("joinHint","Lien de partie invalide.");return}$("joinBtn").disabled=true;setHint("joinHint","Connexion à la partie…");try{peer=makePeer();peer.on("open",()=>{hostConn=peer.connect(roomId,{reliable:true,serialization:"json"});hostConn.on("open",()=>{setHint("joinHint","Connexion établie !");hostConn.send({type:"join",name:me.name})});hostConn.on("data",handleGuestData);hostConn.on("error",e=>{setHint("joinHint",peerErrorMessage(e));$("joinBtn").disabled=false});hostConn.on("close",()=>{toast("La connexion avec l’organisateur a été interrompue.");$("joinBtn").disabled=false;show("join")})});peer.on("error",e=>{setHint("joinHint",peerErrorMessage(e));$("joinBtn").disabled=false})}catch(e){setHint("joinHint","Impossible de rejoindre la partie. Actualisez la page.");$("joinBtn").disabled=false}}
$("createBtn").onclick=createHost;$("startBtn").onclick=startGame;$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText($("shareUrl").value);toast("Lien copié !")}catch{$("shareUrl").select();document.execCommand("copy");toast("Lien copié !")}};$("gameShareBtn").onclick=async()=>{const u=roomLink(roomId);try{await navigator.clipboard.writeText(u);toast("Lien copié !")}catch{toast(u)}};$("joinBtn").onclick=joinRoom;$("rematchBtn").onclick=()=>{if(role==="host"){resetGame();sendState();renderGame();show("game")}else if(hostConn)hostConn.send({type:"rematch"})};$("backBtn").onclick=()=>location.href=location.pathname;
if(new URLSearchParams(location.search).get("room")){show("join");$("joinHint").textContent="Vous avez reçu une invitation à rejoindre une partie."}else show("setup");